### ISSUE TITLE
Will not show the correct mob drops when they are changed by In Control! (1.16)

### ISSUE THREAD

**Issue by GeradesoLukas** [way2muchnoise/JustEnoughResources#331] opened 2022-02-28 13:28 UTC
Hey, so I changed the creeper's mob drops using the [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) mod so that they drop a different item, but now it will not show the correct mob drops.

The Loot I did:

```
[
  {
    "mob": "minecraft:creeper",
    "remove": "minecraft:gunpowder"
  },
  {
    "mob": "minecraft:creeper",
    "player": true,
    "item": "immersiveengineering:dust_sulfur",
    "itemcount": "0-2"
  }
]
```

**Comment by way2muchnoise** [comment] 2022-03-01 17:43
Yeah, really need to get around to supporting this or just having a better grasp on runtime loot tables. Duplicate of #120

**Closed by way2muchnoise** 2022-03-01 17:43 UTC
