### ISSUE TITLE
OOM crash while profiling if there are a large number of dimensions

### ISSUE THREAD

**Issue by maladaptly** [way2muchnoise/JustEnoughResources#192] opened 2019-06-30 21:42 UTC
Just having Galacticraft and Advanced Rocketry installed is probably enough to do it. I cannot post the entire log as it is literally 22 gigabytes, but this is how it ends: https://gist.github.com/maladaptly/9fd95dcb6beeddc1e41991614ee1f9ca

This was 10,000 chunks per dimension.

**Comment by way2muchnoise** [comment] 2019-07-01 08:40
Looks like it might be journeymap
```[journeymap]: Unexpected error in ChunkRenderController: java.lang.OutOfMemoryError: GC overhead limit exceeded```
Were you able to reproduce with JER, Galacticraft and Advanced Rocketry only?

**Comment by maladaptly** [comment] 2019-07-01 13:52
That's only the point at which the runtime finally ran out of memory and had to throw on an allocation. While I can't rule out the possibility that it's leaking memory, that message in itself (or anything in the log, for that matter) doesn't implicate JM at all.

I'll set up another instance with only JER+GC+AR+dependencies but reduce the memory pool size (was 6GB, let's try 3GB) and see what happens.

**Comment by maladaptly** [comment] 2019-07-01 19:59
Reproduced with only JER+GC+AR+dependencies. It got through ~120 dimensions before crashing, so it's not simply a matter of too small a memory pool -- something's either leaking or using memory inefficiently.

Log is once again huge, a whopping 18GB. Here's the tail end:

https://gist.github.com/maladaptly/8aefa783cbc4eac763c5a8dd0e6f8d4d

**Comment by way2muchnoise** [comment] 2019-07-01 20:02
Tbh it kinda makes sense after 120 dim, never really anticipated that. Gonna need to have a long thought about this.

**Comment by way2muchnoise** [comment] 2020-06-20 07:00
Gonna close this one as it was never written for very large scans and needs to be rewritten for newer version anyway

**Closed by way2muchnoise** 2020-06-20 07:00 UTC
