### ISSUE TITLE
[1.16.4] Several tabs missing.

### ISSUE THREAD

**Issue by Corvus20** [way2muchnoise/JustEnoughResources#270] opened 2021-01-02 19:43 UTC
Title says it all. the tabs for mob drops, ore gen, crop drops, and dungeon loot are all missing. The only one thing I can see is the villager trade tab for "uses." Mod version 0.12.0.103, forge version 35.1.28.

**Comment by way2muchnoise** [comment] 2021-01-12 17:26
Duplicate of #269

**Closed by way2muchnoise** 2021-01-12 17:26 UTC
