### ISSUE TITLE
Mod does not disable itself when ran on server side.

### ISSUE THREAD

**Issue by UnicornYames** [way2muchnoise/JustEnoughResources#307] opened 2021-08-12 20:15 UTC
1.16.5

The mod was not disabling itself on server side causing issues where commands would not work. It disabled OP, and would not allow OPs to join the server when opped. I fixed it by removing the mod. But this can be an issue for other hosts.

Make it so your mod doesn't crash servers with errors that take an expert to debug. Please make your mod disable itself gracefully on the server like recommended in the forge documentation (https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods)

**Comment by Planeguy102** [comment] 2021-08-13 08:24
I will mention, I had the same issue. A permanent and completely non-intrusive fix is to simply remove it from the server. I, unfortunately, could not decipher the errors, so ended up randomly slapping at mods to remove them until I fell upon JER. I would ask that you do fix this though, as it will be irritating when it comes time to update the mods.

**Comment by xuwuwudi** [comment] 2021-08-13 09:31
I couldn't believe it was the problem with this mod until I removed it. To be honest, I was a little annoyed because I tried it for nearly an afternoon.

**Comment by toErIpNid** [comment] 2021-08-15 19:38
Can confirm this issue exists, while not opped I can join my server fine, but when opped it causes an internal server error.

**Comment by MorningSage** [comment] 2021-08-18 22:07
I, too, can confirm.

`at jeresources.profiling.ProfileCommand.lambda$register$0(ProfileCommand.java:26) ~[jeresources:0.12.1.127] {re:classloading}`

De-opping solves the problem.  I'll remove from the server next time we restart.

**Comment by Ars2014** [comment] 2021-08-22 18:42
#601341df breaks the server login

**Comment by katykat5099** [comment] 2021-08-22 22:04
Issues persists. Can cause players to not be able to join the server at all.

**Comment by way2muchnoise** [comment] 2021-08-23 10:30
Duplicate of #305

**Closed** 2021-08-23 10:46 UTC
