### ISSUE TITLE
Percentages might be broken

### ISSUE THREAD

**Issue by Peach774** [way2muchnoise/JustEnoughResources#73] opened 2016-07-05 18:48 UTC
I am using reliquary with this mod in 1.10.2. The reliquary items say they have a 10% drop chance in the JustEnoughResources page but they do not seem to be dropping at that rate. Is it on reliquaries side? Or is something wrong with the percentages provided by JustEnoughResources.

**Comment by way2muchnoise** [comment] 2016-07-05 19:57
Is this a drop from chests? Or mobs?

**Comment by Peach774** [comment] 2016-07-05 21:16
Mob, specifically magma slimes say they can drop slime pearls but only regular slimes can

**Comment by way2muchnoise** [comment] 2016-07-05 21:25
Hmm, interesting guess I'll have to take a look at that. Thanks for the report.

**Comment by P3pp3rF1y** [comment] 2016-08-11 11:22
This is likely because I don't use exact match watchabledata when I register the drop to slimes. But with the new loot registration in forge I would actually like JER to load the loot I am adding dynamically to the loot tables. It currently cannot load drops from LootEntryTable so I may do a PR to add this functionality.

**Comment by way2muchnoise** [comment] 2016-08-11 11:41
@P3pp3rF1y Making a PR would be appreciated as I don't have much free time atm

**Comment by P3pp3rF1y** [comment] 2016-08-11 13:28
So LootEntryTable implementation together with the small change from the other ticket (item name comparison in addition to sortindex) seem to do the trick here. This also kind of fixes sheep loot tables as they also have loot table reference in the specific color ones.
However now the issue is that smelt loot function gets just applied because loot functions code doesn't check for conditions. That causes all the smeltable drops that you can get if entity is burning to display instead of the unsmelted ones. 

How would you like to handle this? Just ignore the smelt function in lootdrops? Ideally I would say display both with the tooltip about burning entity on the smelted ones, but based on where this is called currently it seems like that would be a bigger change.

Just for reference this line of code makes for example mutton into cooked mutton when it's added in sheep drops. https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/api/drop/LootDrop.java#L173

**Comment by way2muchnoise** [comment] 2016-08-11 15:07
Can you check out the current implementation, @P3pp3rF1y ? Seems I missed tagged the issue in the commit (ac7378c8b65e971e4c4eacba71c7420124726452). When it has the Smelt loot function it will cycle between both (or focus on one) and added a `When on fire` tooltip when the cooked item rotates in.

**Comment by way2muchnoise** [comment] 2016-08-12 21:33
Fixed in 5ea23f0144a8341bf3466f2210f5489c883a8632

**Closed by way2muchnoise** 2016-08-12 21:33 UTC
Labels: bug
