### ISSUE TITLE
Suggestion : Custom loot file

### ISSUE THREAD

**Issue by Frinn38** [way2muchnoise/JustEnoughResources#135] opened 2017-12-30 15:42 UTC
Hello,
Could it be possible to add a json config file like the world-gen file but to manually change the mob loots displayed in jei. 
Certains mods like in control or loot tweaker can modify the loot tables but the changes are not showed in jer so it will be a cool feature to modify the loots that are showed by jer manually.
Sorry for spelling mistakes I use Google trad.
Thank you by advance.

**Comment by way2muchnoise** [comment] 2017-12-30 16:11
Duplicate of #119 and #120

**Closed by way2muchnoise** 2017-12-30 16:11 UTC

**Comment by Frinn38** [comment] 2017-12-30 16:38
Excuse me but I didn't speak to add an integration to in control and loot tweaker, I just mention those mods for an example of why it could be cool to add an custom mob loot file.

**Comment by way2muchnoise** [comment] 2017-12-30 19:28
I'd rather add some integration, or loading of the current setup after those types of mod did their thing.
Adding more config files that need to be user generated is a really niche solution.
