### ISSUE TITLE
RuntimeException looking at villager trade tab setting unregistered profession

### ISSUE THREAD

**Issue by xenoflot** [way2muchnoise/JustEnoughResources#106] opened 2017-01-17 03:39 UTC
Hi,

I'm getting a CTD when I look at the Uses / Villager Trades tab for ATLCraft Candles Mod's bayberries.
Crash log: https://gist.github.com/xenoflot/f0a4bfdc2e691ebe53fefef77ecba58f

I see in that log the following exception "Attempted to set villager profession to unregistered profession". We had SGCraft in the pack (which adds a villager) but removed it for reasons. I wonder if something isn't handling the removal of that villager elegantly.

The lovely Mezz suggested this was probably one for you to have a look at. https://github.com/mezz/JustEnoughItems/issues/700

atlcraftcandlesmod-1.10.2-ver1.5
jei-1.10.2-3.14.3.402
justenoughcalculation-1.10.2-2.3.2
justenoughresources-1.10.2-0.5.8.98
forge 2185

sgcraft-1.13.2-mc1.10.2 (no longer present in pack)

Cheers!

**Comment by way2muchnoise** [comment] 2017-01-17 09:07
I'll add the atlcraftcandlesmod to my dev env, and see what goes wrong.

**Comment by way2muchnoise** [comment] 2017-02-06 17:38
I can't reproduce this error in my dev env, is there anything changing the villager trades?

![](http://puu.sh/tR7hX/165894f5a5.png)

**Comment by JonathanxD** [comment] 2017-04-29 15:31
The same happened with me but with Actually Additions villager when I tried to see trades of machine casing.

log: https://gist.github.com/JonathanxD/681b043ff49c3826bb9c1fed7262fa32

**Comment by way2muchnoise** [comment] 2019-06-10 13:59
Fixed in 5a8c0e1cbcc7e5f442aed8d78c881ef9170ce6a9

**Closed by way2muchnoise** 2019-06-10 13:59 UTC
Labels: bug, can't reproduce
