### ISSUE TITLE
Client crash with Baubles Stuff

### ISSUE THREAD

**Issue by Liiw** [way2muchnoise/JustEnoughResources#112] opened 2017-04-06 23:20 UTC
Hello!

I experienced a client crash on a modded Spongeforge 1.10.2 server. I was trying to view the recipe for item"Book of Spells" from the mod "Baubles Stuff". I also noticed that the tooltip states that this item is probably a drop from Zombie Pigmen. I am attaching the client crash log:

[crash-2017-04-07_00.16.40-client.txt](https://github.com/way2muchnoise/JustEnoughResources/files/904153/crash-2017-04-07_00.16.40-client.txt)

I reported it to the issues section of "JEI" and I was pointed here.

**Comment by way2muchnoise** [comment] 2017-07-18 14:11
Duplicate of #106

**Closed by way2muchnoise** 2017-07-18 14:11 UTC
