### ISSUE TITLE
[1.12.2] Mob Drop entity not shown fully?

### ISSUE THREAD

**Issue by pimalel233** [way2muchnoise/JustEnoughResources#212] opened 2019-12-25 00:40 UTC
JEI_1.12.2-4.15.0.292.jar
JustEnoughResources-1.12.2-0.8.9.48.jar
Forge-1.12.2-14.23.5.2838-Universal.jar

No ther mods, mob drops looks like this: http://prntscr.com/qfdt82
Any way to fix it? Crop drops seems to show just fine.

**Comment by way2muchnoise** [comment] 2020-01-02 11:03
Update JER to 0.8.10.50 or above, duplicate of #155 and fixed in 684d755de40fe579d80c25bf0fe0f1a776c68075

**Closed by way2muchnoise** 2020-01-02 11:03 UTC
