### ISSUE TITLE
[1.12.2]? Immense unclosed thread flood in process 

### ISSUE THREAD

**Issue by MadProbe** [way2muchnoise/JustEnoughResources#341] opened 2022-05-25 14:30 UTC
When this mod is loaded and post-initialized I see extremely high number of threads opened in minecraft process and most, if not all, do not do any work.
These threads persist until minecraft process closed so I suppose these threads are created and left floafting around in the process without any use.
I don't think this can be caused by Optifine, so please don't reject this issue only because of its existence

Screenshot taken from utility program called [Process Hacker](https://github.com/processhacker/processhacker):
![photo_2022-05-25_17-27-30](https://user-images.githubusercontent.com/49519179/170286870-6704c586-a901-4a00-a674-4ef7c4be1786.jpg)

System configuration / logs:
Minecraft version: 1.12.2
JEI Version: 4.16.1.302
JER Version: 0.9.2.60
latest.log: https://gist.github.com/MadProbe/f8e93c161be3d74738746c41729217f6

**Comment by way2muchnoise** [comment] 2022-05-26 06:03
There is quite a large number of other mods install, what makes you suspect this is JER? Can you reproduce with only JER installed?

Just thinking out loud, but if I recall correct thaumcraft creates a bunch of threads during init.

**Comment by MadProbe** [comment] 2022-05-26 11:33
I have opened this issue only because when I add your mod I can reproduce this issue.
Regarding Thaumcraft: It creates threads for aura calculations in chunks and their number is **equal or less than number of dimensions at world initialization and it closes threads only if dimension inactive (unloaded)**.
But I understand that you request me to check JER only installation and I will write results of my research after some time.

**Comment by MadProbe** [comment] 2022-05-26 15:06
Personally I would mark this issue as mod compat since I have found that somehow your mod and mod named [perfomant](https://www.curseforge.com/minecraft/mc-mods/performant) are causing the issue when they are moth active.
The mods alone don't cause issues but together they somehow conflict and in the result I get a lot of inactive threads which amount depends roughly on count of mods and grows expondentially as count of mods grows.

**Comment by MadProbe** [comment] 2022-05-26 15:16
Personally I would mark this issue with mod compat (or crossmod) label since I have found that somehow your mod and mod named [perfomant](https://www.curseforge.com/minecraft/mc-mods/performant) are causing the issue when they are moth active.
The mods alone don't cause issues but together they somehow conflict and in the result I get a lot of inactive threads which amount depends roughly on count of mods and grows expondentially as count of mods grows.

**Comment by way2muchnoise** [comment] 2022-09-10 12:27
Closing since I don't support 1.12 anymore

**Closed by way2muchnoise** 2022-09-10 12:27 UTC
