### ISSUE TITLE
The Latest Update is Causing World Loading Freeze

### ISSUE THREAD

**Issue by Camawama** [way2muchnoise/JustEnoughResources#326] opened 2022-01-31 00:24 UTC
[2022-01-30-5.log](https://github.com/way2muchnoise/JustEnoughResources/files/7967280/2022-01-30-5.log)

It took me a bit to find the culprit mod, but JER is causing worlds to not load on my modpack after the latest update.

**Comment by egguchan** [comment] 2022-01-31 00:35
Hi, i'm having the same problem. Your log looks incomplete, the error message we get in Issue #325 appears just below the last line in your log, so I suspect it's the same issue. We have to wait around 10 minutes for a small single-player world to load.

**Comment by Pentasis** [comment] 2022-01-31 09:57
Same here. Loading hangs on dirt-screen. Removing JER resolves this.

**Comment by Wedge1453** [comment] 2022-01-31 12:00
tried on forge 39.0.54, 39.0.63, and 39.0.64, same issue

**Comment by Jessman5** [comment] 2022-01-31 16:03
+1 on this
Console is stuck at this line 
` [Render thread/INFO] Registering categories: minecraft:jeresources ...`
while on the dirt screen to join the selected world. 
Occurred after installing latest version 1.18.1-0.13.1.148 but the issue is still there after downgrading back to 147. 

Fixed after downgrading back to 141 version.

**Comment by thebulletprooftiger** [comment] 2022-01-31 16:15
game freezes and crashes on world load. broke modpack. took awhile to find JER as the culprit xD

**Comment by way2muchnoise** [comment] 2022-01-31 16:25
@mezz I though you improved stuff with #322 😆

**Comment by way2muchnoise** [comment] 2022-01-31 19:48
Currently being build and should be up on CF soon. Please validate and close if it works again :)

**Comment by Camawama** [comment] 2022-01-31 21:09
Awesome, I will check this rn. Thank you!

**Comment by way2muchnoise** [comment] 2022-02-02 16:24
Closing as there seem to be no further reports on this issue

**Closed by way2muchnoise** 2022-02-02 16:24 UTC
Labels: bug
