### ISSUE TITLE
Odd issue with GUI?

### ISSUE THREAD

**Issue by TheDeadlyVoid** [way2muchnoise/JustEnoughResources#231] opened 2020-03-25 17:07 UTC
Every time I move my mouse over the 6th row from the top on the GUI, it freezes my game but if I move above or below that row everything works fine. Moving my mouse over that row will not cause my game to crash or unfreeze but it will freeze my game until I move my mouse over or above it. Is this a common issue at all? And how can I fix this? Thank you!

**Comment by way2muchnoise** [comment] 2020-09-05 12:34
Closing due to not enough info, feel free to reopen if you have some reproducible steps. Also please include any other mods (other than JEI ofc)

**Closed by way2muchnoise** 2020-09-05 12:34 UTC
